version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gita-rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset:ro
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - gita-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gita-rag-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gita-network

networks:
  gita-network:
    driver: bridge

volumes:
  transformers_cache:
    driver: local

