[build]
  publish = "frontend/build"
  command = "cd frontend && npm install && npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://bhagwan-gita-summarization-and-verse.onrender.com"
  REACT_APP_TITLE = "Bhagavad Gita RAG Chatbot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://bhagwan-gita-summarization-and-verse.onrender.com"
